import os
import re

def normalize_stem(stem: str) -> str:
    """
    Convert filename stem into a valid Rust constant suffix.
    Example:
        "d'"   -> "D_COMMA"
        "ch'"  -> "CH_COMMA"
        "k'2"  -> "K_COMMA2"
    """
    # Replace apostrophes with _COMMA
    stem = stem.replace("'", "_COMMA")

    # Rust identifiers must be A-Z, 0-9, underscore
    # (if someone uses other weird chars we can sanitize them)
    stem = re.sub(r"[^A-Za-z0-9_]", "_", stem)

    return stem.upper()


def main():
    lang = input("Language folder name (e.g., georgian): ").strip()
    abbr = input("Language abbreviation (e.g., GEO): ").strip().upper()

    folder = f"../assets/langs/{lang}/pronunciation/alphabet"

    if not os.path.isdir(folder):
        print(f"❌ Folder not found: {folder}")
        return

    wav_files = sorted(f for f in os.listdir(folder) if f.lower().endswith(".wav"))

    if not wav_files:
        print(f"❌ No .wav files found in {folder}")
        return

    consts_section = []
    match_section = []

    for filename in wav_files:
        stem = filename[:-4]  # remove .wav
        const_suffix = normalize_stem(stem)
        const_name = f"{abbr}_{const_suffix}"

        consts_section.append(
            f'pub const {const_name}: &[u8] = include_bytes!("../{folder}/{filename}");'
        )

        match_section.append(
            f'        ("{lang}", "{filename}") => Some({const_name}),'
        )

    output_text = []
    output_text.append("// === AUTOGENERATED AUDIO CONSTANTS ===")
    output_text.append("\n// ---- pub const definitions ----\n")
    output_text.extend(consts_section)

    output_text.append("\n\n// ---- match arms for letter_audio_bytes ----\n")
    output_text.extend(match_section)

    out_file = f"generated_audio_constants_{lang}.txt"
    with open(out_file, "w", encoding="utf8") as f:
        f.write("\n".join(output_text))

    print(f"\n✅ Output written to: {out_file}")
    print(f"✔ Found {len(wav_files)} wav files")
    print("✔ Apostrophes converted to '_COMMA'")

if __name__ == "__main__":
    main()
